version: "3"

services:
  db-sandbox:
    image: mariadb:10.3
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - mysql-data-sandbox-fair:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      # MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: root
      # CONFIG - Change the default values below (should match values passed to wikibase)
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'sqlpass'
    networks:
      - sandbox-net
  uris-factory:
    build: ./uris-factory
    container_name: uris-factory
    environment:
      - APP_PERSISTENCE_DATASOURCE_DRIVER-CLASS-NAME=org.mariadb.jdbc.Driver
      - APP_PERSISTENCE_DATASOURCE_USERNAME=app
      - APP_PERSISTENCE_DATASOURCE_PASSWORD=sqlpass
      - APP_PERSISTENCE_DATASOURCE_URL=jdbc:mariadb://db-sandbox/app?ssl=false
    ports:
      - "9326:9326"
    links:
      - "db-sandbox:db-sandbox"
      - "trellis-sandbox:trellis-sandbox"
    depends_on:
      - db-sandbox
      - trellis-sandbox
    networks:
      - sandbox-net
  fuseki-sandbox:
    build: ./fuseki-tdb/
    container_name: fuseki-asio
    restart: always
    environment:
      - ADMIN_PASSWORD=pw123
    ports:
      - "3030:3030"
    volumes:
      - fuseki-data-sandbox-fair:/fuseki/databases/trellis
      - fuseki-backup-sandbox-fair:/fuseki/databases/backups
      #- ./fuseki-conf/config.ttl:/fuseki/config.ttl
      #- ./fuseki-conf/trellis.ttl:/fuseki/trellis.ttl
      #- ./fuseki-conf/shiro.ini:/fuseki/shiro.ttl
      #- ./fuseki-conf/log4j.properties:/fuseki/log4j.properties
    networks:
      - sandbox-net
  trellis-sandbox:
    build: ./trellis
    container_name: trellis
    ports:
      - "8080:8080"
    links:
      - "fuseki-sandbox:fuseki-sandbox"
    depends_on:
      - fuseki-sandbox
    volumes:
      - trellis-data-sandbox-fair:/opt/trellis/data
      - trellis-log-sandbox-fair:/opt/trellis/log
    networks:
      - sandbox-net
#  fuseki-sandbox:
#    build: ./fuseki-tdb/
#    container_name: fuseki-sandbox
#    restart: always
#    environment:
#      - ADMIN_PASSWORD=pw123
#    ports:
#      - "3030:3030"
#    volumes:
#      - fuseki-data-sandbox-fair:/fuseki/databases/trellis
#      - fuseki-backup-sandbox-fair:/fuseki/databases/backups
#      #- ./fuseki-conf/config.ttl:/fuseki/config.ttl
#      #- ./fuseki-conf/trellis.ttl:/fuseki/trellis.ttl
#      #- ./fuseki-conf/shiro.ini:/fuseki/shiro.ttl
#      #- ./fuseki-conf/log4j.properties:/fuseki/log4j.properties
#    networks:
#      - sandbox-net
#  trellis-sandbox:
#    image: trellisldp/trellis-triplestore
#    container_name: trellis
#    restart: always
#    ports:
#      - "8080:8080"
#    environment:
#      - TRELLIS_TRIPLESTORE_RDF_LOCATION=http://fuseki-sandbox:3030/trellis/
#    links:
#      - "fuseki-sandbox:fuseki-sandbox"
#    depends_on:
#      - fuseki-sandbox
#    volumes:
#      - trellis-data-sandbox-fair:/opt/trellis/data
#      - trellis-log-sandbox-fair:/opt/trellis/log
#    networks:
#      - sandbox-net
volumes:
  fuseki-data-sandbox-fair:
  fuseki-backup-sandbox-fair:
  mysql-data-sandbox-fair:
  trellis-data-sandbox-fair:
  trellis-log-sandbox-fair:

networks:
  sandbox-net: