version: '3.7'

services:

  redis:
    restart: unless-stopped
    image: "bitnami/redis:latest"
    ports:
      - "16379:6379"
    environment:
      - REDIS_PASSWORD=j!VxttMdHGhy
    volumes:
      - redis-data:/bitnami/redis/data

volumes:
  redis-data: