version: '3.7'

services:
  discovery-service:
    image: herculescrue/service-discovery:develop
    restart: unless-stopped
    env_file:
      - ./env/global-api.env
      - ./env/service-discovery.env
    ports:
      - "9329:9329"
      - "8089:8080"
#    expose:
#      - "9329"
#      - "8080"
    extra_hosts:
      - "linkeddata1test.um.es:172.19.0.1"
      - "back.um.es:${BACK_HOST}"
      - "db.um.es:${DB_HOST}"

