version: '3.7'

services:

  benchmarks:
    container_name: bechmarks-application
    image: herculescrue/bechmarks:latest
    restart: unless-stopped
    ports:
      - '8081:80'
    expose:
      - '80'
    networks:
      - asionet_front

networks:
  asionet_front:
    name: asio_network_front
