# Wikibase with Query Service
#
# This docker-compose example can be used to pull the images from docker hub.
#
# Examples:
#
# Access Wikibase via "http://localhost:8181"
#   (or "http://$(docker-machine ip):8181" if using docker-machine)
#
# Access Query Service via "http://localhost:8282"
#   (or "http://$(docker-machine ip):8282" if using docker-machine)
version: '3.7'

services:
  wikibase:
    image: wikibase/wikibase:1.34-bundle
    # ports:
    # CONFIG - Change the 8181 here to expose Wikibase & MediaWiki on a different port
    #  - "8181:80"
    expose:
      - "80"
    volumes:
      - mediawiki-images-data:/var/www/html/images
      - quickstatements-data:/quickstatements/data
    restart: unless-stopped
    networks:
      asionet:
        aliases:
         - wikibase.svc
         # CONFIG - Add your real wikibase hostname here, for example wikibase-registry.wmflabs.org
    environment:
      - DB_SERVER=db.um.es:3306
      - MW_ELASTIC_HOST=db.um.es
      - MW_ELASTIC_PORT=9201
      # CONFIG - Change the default values below
      - MW_ADMIN_NAME=WikibaseAdmin
      - MW_ADMIN_PASS=WikibaseDockerAdminPass
      - MW_ADMIN_EMAIL=admin@example.com
      - MW_WG_SECRET_KEY=secretkey
      # CONFIG - Change the default values below (should match mysql values in this file)
      - DB_USER=wiki_as
      - DB_PASS=pkvIStIe!Yw1
      - DB_NAME=wiki_as
      - QS_PUBLIC_SCHEME_HOST_AND_PORT=http://host.docker.internal:9191
    extra_hosts:
      - "back.um.es:${BACK_HOST}"
      - "db.um.es:${DB_HOST}"
  wdqs-frontend:
    image: wikibase/wdqs-frontend:latest
    restart: unless-stopped
    # ports:
    # CONFIG - Change the 8282 here to expose the Query Service UI on a different port
    #  - "8282:80"
    expose:
      - "80"
    depends_on:
    - wdqs-proxy
    networks:
      asionet:
        aliases:
         - wdqs-frontend.svc
    environment:
      - WIKIBASE_HOST=wikibase.svc
      - WDQS_HOST=wdqs-proxy.svc
    extra_hosts:
      - "back.um.es:${BACK_HOST}"
      - "db.um.es:${DB_HOST}"
  wdqs:
    image: wikibase/wdqs:0.3.10
    restart: unless-stopped
    volumes:
      - query-service-data:/wdqs/data
    command: /runBlazegraph.sh
    networks:
      asionet:
        aliases:
         - wdqs.svc
    environment:
      - WIKIBASE_HOST=wikibase.svc
      - WDQS_HOST=wdqs.svc
      - WDQS_PORT=9999
    expose:
      - 9999
    extra_hosts:
      - "back.um.es:${BACK_HOST}"
      - "db.um.es:${DB_HOST}"
  wdqs-proxy:
    image: wikibase/wdqs-proxy
    restart: unless-stopped
    environment:
      - PROXY_PASS_HOST=wdqs.svc:9999
    # ports:
    #  - "8989:80"
    expose:
      - "80"
    depends_on:
    - wdqs
    networks:
      asionet:
        aliases:
         - wdqs-proxy.svc
    extra_hosts:
      - "back.um.es:${BACK_HOST}"
      - "db.um.es:${DB_HOST}"
  wdqs-updater:
    image: wikibase/wdqs:0.3.10
    restart: unless-stopped
    command: /runUpdate.sh
    depends_on:
    - wdqs
    - wikibase
    networks:
      asionet:
        aliases:
         - wdqs-updater.svc
    environment:
     - WIKIBASE_HOST=wikibase.svc
     - WDQS_HOST=wdqs.svc
     - WDQS_PORT=9999
    extra_hosts:
      - "back.um.es:${BACK_HOST}"
      - "db.um.es:${DB_HOST}"
  # CONFING, in order to not load quickstatements then remove this entire section
  quickstatements:
    image: wikibase/quickstatements:latest
    # ports:
    #  - "9191:80"
    expose:
      - "80"
    depends_on:
     - wikibase
    volumes:
     - quickstatements-data:/quickstatements/data
    networks:
      asionet:
        aliases:
         - quickstatements.svc
    environment:
      - QS_PUBLIC_SCHEME_HOST_AND_PORT=http://host.docker.internals:9191
      - WB_PUBLIC_SCHEME_HOST_AND_PORT=http://host.docker.internal:8181
      - WIKIBASE_SCHEME_AND_HOST=http://wikibase.svc
      - WB_PROPERTY_NAMESPACE=122
      - "WB_PROPERTY_PREFIX=Property:"
      - WB_ITEM_NAMESPACE=120
      - "WB_ITEM_PREFIX=Item:"
    extra_hosts:
      - "back.um.es:${BACK_HOST}"
      - "db.um.es:${DB_HOST}"
volumes:
  mediawiki-images-data:
  query-service-data:
  quickstatements-data:

networks:
  asionet:
    external:
      name: asio_network_front
