version: '3.7'

services:

  samltest:
    image: herculescrue/saml-test:latest
    expose:
      - 8080
    ports:
      - 8088:8080
    environment:
      # - SERVER_SERVLET_CONTEXT_PATH=/samltest
      - SERVER_PORT=8080
      - KEYCLOAK_AUTHSERVERURL=https://host.docker.internal:8080/auth
    networks:
      - asionet
 #   extra_hosts:
 #     - "herculesasioizertis.desa.um.es:155.54.239.207"
 #     - "keycloak.herculesasioizertis.desa.um.es:155.54.239.207"
 #     - "samltest.herculesasioizertis.desa.um.es:155.54.239.207"

networks:
  asionet:
    external:
      name: asio_network_front

