version: '3.2'

services:
  agent:
    image: portainer/agent:linux-amd64-2.1.0-alpine
    volumes:
      - \\.\pipe\docker_engine:\\.\pipe\docker_engine
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
