version: '3.7'

services:

  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:3.3
    restart: unless-stopped
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=mycustompepper01
      # Password: admin uoFXoV03%ZMo, asio YlxC^#K!%%2V
      - GRAYLOG_ROOT_PASSWORD_SHA2=86b1d465c6d2b816fa6ac9c59d9f48487335d66ecffb016d4b9cc207c850e426
      - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:9000
      # - GRAYLOG_HTTP_EXTERNAL_URI=http://herc-iz-back-desa.atica.um.es:9000/
      - GRAYLOG_HTTP_EXTERNAL_URI=https://monitorld1test.um.es/
      - GRAYLOG_SERVER_JAVA_OPTS=-Xms512m -Xmx2g -XX:NewRatio=1 -XX:MaxMetaspaceSize=256m -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow
      - GRAYLOG_MONGODB_URI=mongodb://app:password123@db.um.es:27017/graylog
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://db.um.es:9200
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "front.um.es:${FRONT_HOST}"
      - "db.um.es:${DB_HOST}"

  # input-processor
  input-processor:
    # image: umansioacr.azurecr.io/input/input-processor:1.0-SNAPSHOT-69
    image: herculescrue/input-processor:develop
    restart: unless-stopped
    env_file:
      - ./env/global.env
      - ./env/global-api.env
      - ./env/input-processor.env
    expose:
      - "9321"
      - "8080"
    depends_on:
      - graylog
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "front.um.es:${FRONT_HOST}"
      - "db.um.es:${DB_HOST}"

  # management-system
  management-system-pre:
    # image: umansioacr.azurecr.io/event-management/management-system:1.0-SNAPSHOT-73
    image: herculescrue/management-system:develop
    container_name: asio_back_management-system_pre_1
    restart: unless-stopped
    environment:
      - APP_DOMAIN=http://ldp.linkeddata1test.um.es
    env_file:
      - ./env/global.env
      - ./env/global-api.env
      - ./env/management-system.env
    expose:
      - "9321"
      - "8080"
    depends_on:
      - uris-generator
      - graylog
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "front.um.es:${FRONT_HOST}"
      - "db.um.es:${DB_HOST}"

  # uris-generator
  uris-generator:
    # image: umansioacr.azurecr.io/event-management/uris-generator:1.1.0-33
    image: herculescrue/uris-generator:develop
    restart: unless-stopped
    environment:
      - APP_PERSISTENCE_JPA_GENERATEDDL=true
      - APP_URI_CANONICALURISCHEMA=$$domain$$/$$sub-domain$$/$$type$$/$$concept$$/$$reference$$
      - APP_URI_CANONICALURILANGUAGESCHEMA=$$domain$$/$$sub-domain$$/$$language$$/$$type$$/$$concept$$/$$reference$$
    env_file:
      - ./env/global.env
      - ./env/global-api.env
      - ./env/uris-generator.env
    expose:
      - "9321"
      - "8080"
    extra_hosts:
      - "ldp.linkeddata1test.um.es:172.19.0.1"
      - "host.docker.internal:host-gateway"
      - "front.um.es:${FRONT_HOST}"
      - "db.um.es:${DB_HOST}"
    depends_on:
      - graylog

  #federation
  federation:
    image: herculescrue/federation:develop
    restart: unless-stopped
    env_file:
      - ./env/federation.env
    ports:
      - "9328:9328"
      - "8388:8080"
    expose:
      - "9328"
      - "8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "front.um.es:${FRONT_HOST}"
      - "db.um.es:${DB_HOST}"

  # discovery
  discovery:
    # image: umansioacr.azurecr.io/event-management/discovery:1.0-SNAPSHOT-22
    image: herculescrue/discovery:develop
    restart: unless-stopped
    env_file:
      - ./env/discovery.env
    ports:
      - "9327:9327"
      - "8087:8080"
    expose:
      - "9327"
      - "8080"
    depends_on:
      - graylog
      - uris-generator
      - federation
      - elasticsearch
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "front.um.es:${FRONT_HOST}"
      - "db.um.es:${DB_HOST}"

  # elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    restart: unless-stopped
    environment:
      - cluster.name=es-asio-cluster
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9213:9200
      - 9313:9300
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "front.um.es:${FRONT_HOST}"
      - "db.um.es:${DB_HOST}"

  # kibana
  kibana:
    restart: unless-stopped
    image: docker.elastic.co/kibana/kibana:6.5.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "front.um.es:${FRONT_HOST}"
      - "db.um.es:${DB_HOST}"

  # trellis-event-processor
  trellis-event-processor:
    #image: umansioacr.azurecr.io/event-management/event-processor:1.0-SNAPSHOT-47
    image: herculescrue/event-processor:develop
    restart: unless-stopped
    env_file:
      - ./env/global.env
      - ./env/event-processor.env
      - ./env/trellis-event-processor.env
    expose:
      - "9321"
    depends_on:
      - trellis-storage-adapter
      - graylog
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "front.um.es:${FRONT_HOST}"
      - "db.um.es:${DB_HOST}"

  # trellis-storage-adapter
  trellis-storage-adapter:
    # image: umansioacr.azurecr.io/event-management/triples-storage-adapter:1.0-SNAPSHOT-57
    image: herculescrue/triples-storage-adapter:develop
    restart: unless-stopped
    env_file:
      - ./env/global.env
      - ./env/global-api.env
      - ./env/storage-adapter.env
      - ./env/trellis-storage-adapter.env
    expose:
      - "9321"
      - "8080"
    environment:
      - APP_DOMAIN=http://ldp.linkeddata1test.um.es
      - APP_GENERATORURIS_ENDPOINT=http://uris-generator:8080
    extra_hosts:
      - "ldp.linkeddata1test.um.es:172.19.0.1"
      - "host.docker.internal:host-gateway"
      - "front.um.es:${FRONT_HOST}"
      - "db.um.es:${DB_HOST}"
    depends_on:
      # - trellis
      - graylog

  # wikibase-event-processor
  wikibase-event-processor:
    # image: umansioacr.azurecr.io/event-management/event-processor:1.0-SNAPSHOT-47
    image: herculescrue/event-processor:develop
    restart: unless-stopped
    env_file:
      - ./env/global.env
      - ./env/event-processor.env
      - ./env/wikibase-event-processor.env
    expose:
      - "9321"
    depends_on:
      - wikibase-storage-adapter
      - graylog
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "front.um.es:${FRONT_HOST}"
      - "db.um.es:${DB_HOST}"

  # wikibase-storage-adapter
  wikibase-storage-adapter:
    # image: umansioacr.azurecr.io/event-management/triples-storage-adapter:1.0-SNAPSHOT-57
    image: herculescrue/triples-storage-adapter:develop
    restart: unless-stopped
    env_file:
      - ./env/global.env
      - ./env/global-api.env
      - ./env/storage-adapter.env
      - ./env/wikibase-storage-adapter.env
    expose:
      - "9321"
      - "8080"
    depends_on:
      - graylog
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "front.um.es:${FRONT_HOST}"
      - "db.um.es:${DB_HOST}"

  # web-publication-backend
#  web-publication-backend:
#    image: umansioacr.azurecr.io/web-publication/web-publication-backend:1.0-SNAPSHOT-20
#    restart: unless-stopped
#    env_file:
#      - ./env/global.env
#      - ./env/global-api.env
#      - ./env/web-publication-backend.env
#    ports:
#      - "8787:8080"
#    expose:
#      - "9321"
#      - "8080"
#    depends_on:
#      - graylog

volumes:
  elasticsearch-data:
    driver: local
