version: '3.7'

services:

  pdi:
    image: herculescrue/pdi:9.0
    restart: unless-stopped
    ports:
      - "18080:8080"
    volumes: 
      - ./pdi/repositories:/pentaho-di/repositories
      - ./pdi/kettle.properties:/pentaho-di/.kettle/kettle.properties
    environment: 
      - CARTE_NAME=master1
      - CARTE_HOSTNAME=localhost
      - CARTE_USER=asioetl
      - CARTE_PASSWORD=asioetl
      - REPOSITORY_NAME=ASIO-UM
      - REPOSITORY_BASE_DIRECTORY=/pentaho-di/repositories/asio-um/project
      - TZ=Europe/Madrid
    extra_hosts:
      - "back.um.es:${FRONT_HOST}"
      - "db.um.es:${DB_HOST}"