version: '3.7'

services:

  nginx:
    container_name: nginx
    image: 'nginx:alpine'
    ports: 
      - "80:80"
      - "443:443"
      # - "8443:8443"
    volumes:
      - './conf.d:/etc/nginx/conf.d'
      - './certsm:/etc/nginx/certs'
      - './certs.ss:/etc/nginx/certs.ss'
      - './conf:/etc/nginx/confff'
    restart: always
    networks:
      - asionet

networks:
  asionet:
    external:
      name: asio_network
