version: '3.7'

services:
  portainer:
    image: portainer/portainer-ce:2.1.1-alpine
    restart: unless-stopped
    # ports:
    #   - 9001:9000
    #   - 8001:8000
    expose:
      - 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - asionet

volumes:
  portainer_data:

networks:
  asionet:
    external:
      name: asio_network_front
