# Wikibase with Query Service
#
# This docker-compose example can be used to pull the images from docker hub.
#
# Examples:
#
# Access Wikibase via "http://localhost:8181"
#   (or "http://$(docker-machine ip):8181" if using docker-machine)
#
# Access Query Service via "http://localhost:8282"
#   (or "http://$(docker-machine ip):8282" if using docker-machine)
version: '3'

services:
  wb-wikibase-IO:
    image: wikibase/wikibase:1.35-bundle
    links:
      - wb-mysql
    ports:
      # CONFIG - Change the 8181 here to expose Wikibase & MediaWiki on a different port
      - "18484:80"
    volumes:
      - wb-mediawiki-images-data:/var/www/html/images
      - wb-quickstatements-data:/quickstatements/data
    depends_on:
      - wb-mysql
      - wb-elasticsearch
    restart: unless-stopped
    networks:
      bwikibase:
        aliases:
          - wb.wikibase.svc
          # CONFIG - Add your real wikibase hostname here, only for internal names and when NOT terminating SSL outside the container.
    environment:
      - DB_SERVER=host.docker.internal:3316
      - MW_ELASTIC_HOST=host.docker.internal
      - MW_ELASTIC_PORT=9202
      # CONFIG - Change the default values below
      - MW_ADMIN_NAME=WikibaseAdmin
      - MW_ADMIN_PASS=WikibaseDockerAdminPass
      - MW_ADMIN_EMAIL=admin@example.com
      - MW_WG_SECRET_KEY=secretkey
      # CONFIG - Change the default values below (should match mysql values in this file)
      - DB_USER=wikiuser
      - DB_PASS=sqlpass
      - DB_NAME=my_wiki
      - QS_PUBLIC_SCHEME_HOST_AND_PORT=http://wb-quickstatements-data:29191
  wb-mysql:
    image: mariadb:10.3
    restart: unless-stopped
    ports:
      - 3316:3306
    volumes:
      - wb-mediawiki-mysql-data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      # CONFIG - Change the default values below (should match values passed to wikibase)
      MYSQL_DATABASE: 'my_wiki'
      MYSQL_USER: 'wikiuser'
      MYSQL_PASSWORD: 'sqlpass'
    networks:
      bwikibase:
        aliases:
          - wb.mysql.svc
  wb-elasticsearch:
    image: wikibase/elasticsearch:6.5.4-extra
    restart: unless-stopped
    ports:
      - 9202:9200
      - 9302:9300
    networks:
      bwikibase:
        aliases:
          - wb.elasticsearch.svc
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  # CONFING, in order to not load quickstatements then remove this entire section
  wb-wdqs-frontend-IO:
    image: wikibase/wdqs-frontend:latest
    restart: unless-stopped
    ports:
      # CONFIG - Change the 8282 here to expose the Query Service UI on a different port
      - "18585:80"
    depends_on:
      - wb-wdqs-proxy-IO
      - wb-wikibase-IO
    networks:
      bwikibase:
        aliases:
          - wb.wdqs-frontend.svc
    environment:
      - WIKIBASE_HOST=wb-wikibase-IO
      - WDQS_HOST=wb-wdqs-proxy-IO
  wb-wdqs-IO:
    image: wikibase/wdqs:0.3.40
    restart: unless-stopped
    volumes:
      - wb-query-service-data:/wdqs/data
    command: /runBlazegraph.sh
    networks:
      bwikibase:
        aliases:
          - wb.wdqs.svc
    depends_on:
      - wb-wikibase-IO
    environment:
      - WIKIBASE_HOST=wb.wikibase.svc
      - WDQS_HOST=wb.wdqs.svc
      - WDQS_PORT=9999
    expose:
      - 9999
  wb-wdqs-proxy-IO:
    image: wikibase/wdqs-proxy
    restart: unless-stopped
    environment:
      - PROXY_PASS_HOST=wb-wdqs-IO:9999
    ports:
      - "28989:80"
    depends_on:
      - wb-wdqs-IO
    networks:
      bwikibase:
        aliases:
          - wb.wdqs-proxy.svc
  wb-wdqs-updater-IO:
    image: wikibase/wdqs:0.3.40
    restart: unless-stopped
    command: /runUpdate.sh
    depends_on:
      - wb-wdqs-IO
      - wb-wikibase-IO
    networks:
      bwikibase:
        aliases:
          - wb.wdqs-updater.svc
    environment:
      - WIKIBASE_HOST=wb.wikibase.svc
      - WDQS_HOST=wb.wdqs.svc
      - WDQS_PORT=9999

  wb-quickstatements-IO:
    image: wikibase/quickstatements:latest
    ports:
      - "29191:80"
    depends_on:
      - wb-wikibase-IO
    volumes:
      - wb-quickstatements-data:/quickstatements/data
    networks:
      bwikibase:
        aliases:
          - wb.quickstatements.svc
    environment:
      - QS_PUBLIC_SCHEME_HOST_AND_PORT=http://wb.quickstatements.svc:29191
      - WB_PUBLIC_SCHEME_HOST_AND_PORT=http://localhost:8181
      - WIKIBASE_SCHEME_AND_HOST=http://wb.wikibase.svc
      - WB_PROPERTY_NAMESPACE=122
      - "WB_PROPERTY_PREFIX=Property:"
      - WB_ITEM_NAMESPACE=120
      - "WB_ITEM_PREFIX=Item:"

volumes:
  wb-mediawiki-mysql-data:
  wb-mediawiki-images-data:
  wb-query-service-data:
  wb-quickstatements-data:

networks:
  bwikibase:
